# Generated by Django 2.0.6 on 2019-09-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_author_bookmanytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='author', to='app03.Book'),
        ),
    ]
