"""
Django settings for Djframework project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8n8^@_jk8$!x%*2283!-@l*vw&nq2cm1_xqn!lz=^in+2#ki!#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
    'api.apps.ApiConfig',
    'rest_framework',
    'api02.apps.Api02Config',
    'rabbitmq',
    'djcelery',
    'AliOss.apps.AliossConfig',
    'AliPayStudy.apps.AlipaystudyConfig',
    'PayPalStudy.apps.PaypalstudyConfig',
    'modelsUpload.apps.ModelsuploadConfig',
    'paypal.standard.ipn',
]

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # # 自定义第一个中间件
    # 'middleware.middlewarestudy.middlewareStudy.middlewareStudy',
    # # 自定义第二个中间件
    # 'middleware.middlewarestudy.middlewareStudy.middlewareStudy2'

]

ROOT_URLCONF = 'Djframework.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Djframework.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'HOST': '127.0.0.1',
    #     'PORT': 3306,
    #     'NAME': 'DjangoFramework',
    #     'USER': 'root',
    #     'PASSWORD': ''
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':'192.168.118.169',
        'PORT':3603,
        'NAME':'DjangoFramework',
        'USER':'dev',
        'PASSWORD':'123456'
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    # 全局使用的认证类
    "DEFAULT_AUTHENTICATION_CLASSES":['api.utils.auth.FirstAuthotication','api.utils.auth.Authotication'],
    # 匿名用户设置
    # "UNAUTHENTICATED_USER":lambda : "匿名用户"
    "UNAUTHENTICATED_USER":None, # 匿名或者未登录，结果request.user = None
    "UNAUTHENTICATED_TOKEN":None, # 匿名或者未登录，结果request.auth = None
    # 设置全局使用权限类
    "DEFAULT_PERMISSION_CLASSES":['api.utils.Permission.SVIPPermisson'],
    # 设置全局使用访问次数
    "DEFAULT_THROTTLE_CLASSES": ['api.utils.Throttle.UserVisteThrottle'],
    # 全局使用内置访问次数限制
    "DEFAULT_THROTTLE_RATES":{
        # 一分钟访问3次，JimLimit记录的key，对应访问限制类里面的scope
        "JimLimit": '3/m',
        "JimLimitUser": '10/m'
    },
    # 默认版本号
    "DEFAULT_VERSION":'v1',
    # 允许通过的版本
    "ALLOWED_VERSIONS":['v1','v2'],
    # 版本key
    "VERSION_PARAM":'version',
    # 根据urls.py控制版本
    "DEFAULT_VERSIONING_CLASS":"rest_framework.versioning.URLPathVersioning",
    # 全局解析器使用方法
    "DEFAULT_PARSER_CLASS":["rest_framework.parsers.JSONParser","rest_framework.parsers.FormParser","rest_framework.parsers.MultiPartParser","rest_framework.parsers.FileUploadParser"],
    #分页数
    "PAGE_SIZE" : 2,
    # 以json方法显示页码:JSONRenderer,浏览器看数据：BrowsableAPIRenderer
    "DEFAULT_RENDERER_CLASSES":['rest_framework.renderers.JSONRenderer','rest_framework.renderers.BrowsableAPIRenderer'],
}

# # Celery
from .celeryconfig import *
BROKER_URL = 'amqp://jim:jim@39.108.147.32:5672/test1'
CELERY_RESULT_BACKEND = 'amqp://jim:jim@39.108.147.32:5672/test1'

# 若未指定上传文件目录，我们也可以指定MEDIA_ROOT,就不需要指定upload_to,会自动将文件上传到MEDIA_ROOT目录
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# 此付款机制作为测试用
PAYPAL_TEST = True
# 设置收款的 PayPal 电子邮件账户
PAYPAL_REVEIVER_EMAIL = '1657210793-facilitator@qq.com'
