# Generated by Django 2.2.4 on 2019-09-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='广州市', max_length=255),
        ),
    ]
