# Generated by Django 2.2.4 on 2019-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0003_publisher_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('book', models.ManyToManyField(to='BookManageAppp.Book')),
            ],
        ),
    ]
