# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0006_auto_20190908_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default='99.99', max_digits=5),
        ),
    ]
