# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0008_auto_20190908_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_book', to='BookManageAppp.Publisher'),
        ),
    ]
