# Generated by Django 2.0.6 on 2019-09-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0009_auto_20190908_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kuncun',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='maichu',
            field=models.IntegerField(default=0),
        ),
    ]
