# Generated by Django 2.0.6 on 2019-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0010_auto_20190909_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('book', models.ManyToManyField(to='BookManageAppp.Book')),
            ],
        ),
    ]
