# Generated by Django 2.0.6 on 2019-09-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0011_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author2',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author2',
        ),
    ]
