# Generated by Django 2.0.6 on 2019-09-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookManageAppp', '0012_auto_20190909_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
