# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='EmployeeNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('salary', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=32)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app05.dept')),
            ],
            options={
                'db_table': 'employeeNew',
            },
        ),
    ]
