# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0003_auto_20190910_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_cn', models.CharField(max_length=32)),
                ('city_en', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='dept2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'dept2',
            },
        ),
        migrations.CreateModel(
            name='EmployeeNew2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('salary', models.CharField(max_length=32)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app05.dept2')),
            ],
            options={
                'db_table': 'employeeNew2',
            },
        ),
        migrations.CreateModel(
            name='EmployeeNew2City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app05.City')),
                ('EmployeeNew2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app05.EmployeeNew2')),
            ],
        ),
    ]
