# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0004_city_dept2_employeenew2_employeenew2city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeenew2',
            name='city',
            field=models.ManyToManyField(related_name='provinceManyToMany', through='app05.EmployeeNew2City', to='app05.City'),
        ),
    ]
