# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0005_employeenew2_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='employeenew2city',
            table='EmployeeNew2City',
        ),
    ]
