# Generated by Django 2.2.4 on 2019-09-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
