# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 06:58
from __future__ import unicode_literals

import app01.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_persion'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpersion',
            name='chars',
            field=app01.models.FixedCharField(default='chars', max_length=32),
        ),
    ]
