# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_newpersion_chars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newpersion',
            table='test_newPersion',
        ),
    ]
